### ISSUE TITLE
Rochen logo not showing

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla.org#12]
The image path is `https://cdn.joomla.org/rochen/rochen_footer_logo_white.png` which doesn't seem to exist:

![untitled](https://cloud.githubusercontent.com/assets/2019801/24797987/b111058a-1b8b-11e7-8347-5d17263526ff.png)

**Comment by MATsxm** [comment]
CDN issue
https://github.com/joomla/joomla-websites/issues/918
