### ISSUE TITLE
Add a multi-language support on the main site.

### ISSUE THREAD

**Issue by sujit-jaunjal** [joomla/joomla.org#47]
What needs to be fixed
Multi-language support

Why this should be fixed
So that more users can access this site and follow it.

How would you fix it
Use the google translate api and place it at proper place on the mainpage.

Side Effects expected
Other UI component's space might be reduced while implementing translate box.

**Comment by shitesh2607** [comment]
Hi @sujit-jaunjal, How to set this joomla.org on local server because there is no description regarding setup

**Comment by Octopops2442** [comment]
hello @sujit-jaunjal, can I work on this issue?

**Comment by omduragkar** [comment]
Hey @conconnl , Would love to work on this issue can I start to work on this? 
Thanks,
Om

**Comment by shagungarg0** [comment]
Can i work on this issue?

**Comment by shivam969619** [comment]
hey can you assing me this issue

**Comment by HLeithner** [comment]
I'm closing this because it will be considered at a later relaunch.
