### ISSUE TITLE
Adding  README file to joomla.org

### ISSUE THREAD

**Issue by avinash201199** [joomla/joomla.org#49]
@zero-24 @mbabker @conconnl 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by avinash201199** [comment]
@zero-24 @mbabker @conconnl
Please assign this task to me . I would love to contribute in your organization .
Thank you.

**Comment by conconnl** [comment]
Thanks for you request.

Anybody in the community can create Pull Requests to suggest changes in various places.
If you have suggestions for the Readme file in this repository which just holds the custom parts of the website as storage, you could create a PR.
