### ISSUE TITLE
J4Landing - Dropdown bug

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla.org#55]
The dropdown menuitems of the new landing page does not collaps, when you click a new parent item. Happens in Chrome and Firefox.
![dropdown](https://user-images.githubusercontent.com/1399437/129542996-8dcd88a1-b032-4db2-8842-14b72d8aff7b.PNG)

**Comment by conconnl** [comment]
Solved, it will be visible when the cache refreshes.
