### ISSUE TITLE
Search results do not show the last character of article title that contains apostophe

### ISSUE THREAD

**Issue by mwlandolsi** [joomla/joomla.org#78]
Hello
This my first post, and I hope that it will be useful.
After testing it on tow of my sites that uses the last Joomla version 3.10.3 , I have noticed that when the article title contains an apostrophe ( ' ) then the last character of the title is truncated in search results. Second issue is that when adding a space at the end of the title, three points "..." are added to the end of the title of the article in search results.

Here is an example : 
https://conceptec.net/fr/accueil/rechercher?searchword=conception%20pi%C3%A8ce%20plastique&searchphrase=all

**Comment by yuvraj-singh08** [comment]
It's because the apostrophe(') in the searched text messes with the apostrophe in the php code.

So, when it stores the data in the variable like $_GET['search'] = 'conception pièce plastique's'; so it will only store text before the apostrophe(').

**Comment by mwlandolsi** [comment]
Thanks for your answer. This is the cause, but is there a solution?

**Comment by conconnl** [comment]
Great that you are helping each other.
This is the repository specifically for the Joomla.org main website.
I will close it to show others that we don't have an issue with the website, but it can still be used by you two.
