### ISSUE TITLE
Typo in `/contribute-to-joomla.html`.

### ISSUE THREAD

**Issue by ankur12-1610** [joomla/joomla.org#81]
![joomla](https://user-images.githubusercontent.com/76884959/155674419-ac81ab5a-53e8-4579-b282-b9d7f3fdcace.png)

There is a typo in `contact` which written as `conntact`.

URL: `/contribute-to-joomla.html`

**Comment by ankur12-1610** [comment]
I'll like to work on it.

**Comment by conconnl** [comment]
Thank you, it's updated
