### ISSUE TITLE
language translations not added because github action is disabled

### ISSUE THREAD

**Issue by TLWebdesign** [joomla/joomla.org#88]
Hi,

Can someone please activate the github workflow (actions) on the link below so we can get the language translations inside crowdin? 

https://github.com/joomla/joomla.org/actions/workflows/crowdin-wf-j4landing.yml

**Comment by HLeithner** [comment]
thanks to george, who fixed it.,

**Comment by TLWebdesign** [comment]
Yeah i saw it. thanks very much!
