### ISSUE TITLE
Wrong link in announcement to J5 RC download

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla.org#91]
In the announcement of J5 RC the first link to the download test package has an extra 1 at the end of the link.
Also it is described as beta some sentences down the page.
https://www.joomla.org/announcements/release-news/5895-joomla-5-0-release-candidate-test-the-final-package.html

See attached screenshot
![Joomla-5-RC-news-issues](https://github.com/joomla/joomla.org/assets/790445/0620032c-2d09-4c01-b38a-f721b2462fb4)

**Comment by HLeithner** [comment]
Fixed thanks

**Comment by ot2sen** [comment]
Text fixed, first link still has the extra 1
href="https://github.com/joomla/joomla-cms/releases/tag/5.0.0-rc1">Joomla 5.0 Release Ca
which doesn´t work, but it does without the 1 :)
href="https://github.com/joomla/joomla-cms/releases/tag/5.0.0-rc">Joomla 5.0 Release Ca

**Comment by HLeithner** [comment]
ah seems I missed the first one... thanks
